### ISSUE TITLE
[PUBLIC WEB] Inquire Guide Button - Missing

### ISSUE THREAD

**Issue by mque12** [tralulu/bugs#11]
*** Scenario ***

After I click the inquire guide, I would receive a prompt na saving inquiry......
then directed to the chat box. 
--- Booking Guide, so I have to click pa the Inquiry Tab
--- If bumalik ako sa profile ni guide, The Inquiry Button is Missing. 

*** Expected Behavior ***
The Inquiry button should be there at all times. 

![inquire_guide_buttorn_missing](https://cloud.githubusercontent.com/assets/11516068/18458664/4d4910bc-7995-11e6-8de2-ea4d69eacdc6.png)

**Comment by kristianguevara** [comment]
Already fixed this one. If the inquire guide is already clicked once, it will change to "chat guide" button

![screen shot 2016-09-13 at 6 27 28 pm](https://cloud.githubusercontent.com/assets/3320659/18470598/d44f5d1a-79df-11e6-862e-e860ad766129.png)
