### ISSUE TITLE
[PUBLIC WEB] Button Missing if Booked

### ISSUE THREAD

**Issue by mque12** [tralulu/bugs#12]
*** Scenario ***
When Booked, then I go back to his profile, everything is missing.

*** Expected Behavior ***
Both Booking button and Inquiry should still be there.
Or instead of Book this guide --> Review Booking 

![button_missing_if_booked](https://cloud.githubusercontent.com/assets/11516068/18458680/943b3248-7995-11e6-8a48-0dcf8a2bd0b9.png)

**Comment by kristianguevara** [comment]
It once had a button there to review booking but thanks for this will revisit and fix it

**Comment by kristianguevara** [comment]
FIxed
