### ISSUE TITLE
[PUBLIC WEB] Inquire Button - Took a while

### ISSUE THREAD

**Issue by mque12** [tralulu/bugs#14]
**Scenario**
I was planning to chat the guide, but it took me a few minutes before entering chat box. 
so, i thought Internet problem, so i open several tabs, then click the inquire button multiple times,
then I got several [Prompt box] saying na inquiry successful.

So nag open ako ng maraming tabs, then clinick ko ung inquire guides, then after cguro 5-10 mins, tsaka lang nag load properly. ----> 5 alert box ng saved inquiry

Mark Que ---- Marvin Bunaton

**Expected Behavior**
Regardless of how many time i click it, one chat box only. 
I think this is a bug?  

![image](https://cloud.githubusercontent.com/assets/11516068/18536149/1839d296-7b2d-11e6-98db-68a969234970.png)

**Comment by kristianguevara** [comment]
The chat should be somewhat stable from this point stable. I'm not sure how you did it but definitely the requirement is the guide should be online. Did you had a guide account logged-in through another browser?
