### ISSUE TITLE
[PUBLIC WEB] Guide Rating Problem

### ISSUE THREAD

**Issue by mque12** [tralulu/bugs#2]
*** Scenario *** The rating of the guide presented when I search them, is different from the rating inside the profile of the guide

***Expected Behavior ***
It should be the same.

![guide_rating_problem](https://cloud.githubusercontent.com/assets/11516068/18458010/04fba220-7990-11e6-834b-149d6affcba7.png)

**Comment by blouiecubero** [comment]
This one is already been fixed in my version. Waiting for xtian to merge changes.
