### ISSUE TITLE
[PUBLIC WEB] - USER SIDE - Profile Language Edit

### ISSUE THREAD

**Issue by mque12** [tralulu/bugs#22]
** Scenario**
1. Confused, Bakit walang languages sa guide side?
2. Medyo matagal pala mag upload ng language.

**Expected Behavior **
Faster upload 

![image](https://cloud.githubusercontent.com/assets/11516068/18616627/e66bcf5e-7df1-11e6-827b-bd0a6bcb18ab.png)

**Comment by kristianguevara** [comment]
The uploading percentage only appears when you upload an image. In your case I'm assuming you did an image upload before you tried to modify the language. Anyways if the upload progress seemed confusing, it should be addressed from the previous ticket (related to this).
