### ISSUE TITLE
[PUBLIC WEB]- User Side - Profile Edit

### ISSUE THREAD

**Issue by mque12** [tralulu/bugs#23]
**Scenario**

I edit my profile, then click update profile, waited mga 1-3 secs. **parang walang ngyayari.** 

waited around 30 sec. I received the alert box. 
[Success]
After it reload, wala nmn lumabas. when i click edit profile again. **Hindi rin siya na save**

**Expected Behavior**

There's something na mag sasabi sakin na it's saving. -- -> GIF?

I want to see it in my profile. 
Update: Ohh lumalabas pala, pero u have to refresh it. (Hindi siya mag chchange even after mag reload ung page after clicking Update Profile)

![image](https://cloud.githubusercontent.com/assets/11516068/18616643/3cab8526-7df2-11e6-949d-5e2498c1d494.png)
![image](https://cloud.githubusercontent.com/assets/11516068/18616654/6eed17ac-7df2-11e6-8990-81d0ee4344fb.png)

**Comment by kristianguevara** [comment]
Fixed. Already reflected on the test env. Closing
