### ISSUE TITLE
[PUBLIC WEB] - USER SIDE - No language fee for Mr Bonatum

### ISSUE THREAD

**Issue by mque12** [tralulu/bugs#25]
** Scenario **
Nag add ako ng language

** Expected Behavior**
Mag increase ung price

![image](https://cloud.githubusercontent.com/assets/11516068/18616792/3dee36ac-7df4-11e6-9c17-b754e9338f36.png)

**Comment by kristianguevara** [comment]
This ain't a bug. You can add languages on the admin portal as well as by following the CSV format. If no prices are added by default it results to 0. To be closed
