### ISSUE TITLE
[PUBLIC WEB] Guide Profile Details - Wrong Alignment

### ISSUE THREAD

**Issue by mque12** [tralulu/bugs#3]
*** Scenario ***
Inside the Profile of the Guides, Wrong Alignment if they have Multiple Language.

*** Expected Behavior ***
Proper Alignment depending on the content. 
Sana hindi ma disalign, even if I add 10 Languages, etc

![wrong_alignment](https://cloud.githubusercontent.com/assets/11516068/18458076/91704ca6-7990-11e6-9b15-a08d3403bb74.png)

**Comment by kristianguevara** [comment]
Already addressed
