### ISSUE TITLE
[PUBLIC WEB] - User Side - Consistency in "Chat/Inquire Guide"

### ISSUE THREAD

**Issue by mque12** [tralulu/bugs#35]
**Scenario**
Different guides iba iba yung nasa "Chat button"
Some Guides - "Inquire Guides"
Some Guides - "Chat Guides"

**Expected Behavior**
Same for all the Guides

![image](https://cloud.githubusercontent.com/assets/11516068/18808606/205c82de-8299-11e6-8a08-5dba299d4f29.png)

![image](https://cloud.githubusercontent.com/assets/11516068/18808609/2aab021a-8299-11e6-812e-4681b2b096be.png)

![image](https://cloud.githubusercontent.com/assets/11516068/18808615/3d68e688-8299-11e6-861d-98635b0dfdee.png)

![image](https://cloud.githubusercontent.com/assets/11516068/18808618/484aec2c-8299-11e6-9f7a-5186d0d3495d.png)

**Comment by kristianguevara** [comment]
Will take this concurrently with #36 as both work hand-in-hand

**Comment by kristianguevara** [comment]
Done 👍  Tested out with various scenarios together with #36
