### ISSUE TITLE
[PUBLIC WEB] - USER SIDE - Both INQUIRE/CHAT Button Bug

### ISSUE THREAD

**Issue by mque12** [tralulu/bugs#36]
**Scenario**
Okay naman siya, nung naka log in ako. but when i tried it nung nakalog out na ako. 
This is the outcome.
Both Inquire and Chat Button. Andyan

**Expected Behavior**
One Button only, khit naka log-in ako or not.

![image](https://cloud.githubusercontent.com/assets/11516068/18808631/aa8cb7bc-8299-11e6-88d8-81375bba5970.png)

**Comment by kristianguevara** [comment]
Will do this now since its a pre-requisite to the other bug I'm doing :D
