### ISSUE TITLE
[PUBLIC WEB] - USER SIDE - Hide "Your Rating" - if Hindi pa naka Log-in

### ISSUE THREAD

**Issue by mque12** [tralulu/bugs#37]
**Scenario**
Even if hindi ako naka log in, i can still see the "Your Rating" part

**Expected Behavior**
Hide it, 
I hope visible lang siya if naka Log-in na ako.

![image](https://cloud.githubusercontent.com/assets/11516068/18808645/148f35cc-829a-11e6-9d0d-f9a5de08eb1e.png)

**Comment by kristianguevara** [comment]
All good

![screen shot 2016-09-26 at 9 58 34 pm](https://cloud.githubusercontent.com/assets/3320659/18836898/74e257c4-8434-11e6-8b66-e6ce780fd3f7.png)
