### ISSUE TITLE
[PUBLIC WEB] - User Side - More info about the Guide

### ISSUE THREAD

**Issue by mque12** [tralulu/bugs#40]
**Scenario**
_As a traveler, i want to see more info about the guide._ 

**Expected Behavior**
_More info about the guide_
Last active - could encourage the guides to go online everyday. :D 

![image](https://cloud.githubusercontent.com/assets/11516068/18823443/bcf3db5c-83ec-11e6-864d-0d8d2654525b.png)

**Comment by kristianguevara** [comment]
Added the remaining fields :+1: let me know if there's any info needed for this part to be displayed.

![screen shot 2016-09-26 at 9 45 36 pm](https://cloud.githubusercontent.com/assets/3320659/18836435/a3c85a5e-8432-11e6-84e2-0b8dcf7044f4.png)
