### ISSUE TITLE
[PUBLIC WEB] - User Side - Add a section where i can see my selected dates.

### ISSUE THREAD

**Issue by mque12** [tralulu/bugs#43]
**Scenario**
Hindi ko makita ung mga pinili kong dates

**Expected Behavior**
When I choose the dates, i want to see lahat ng napili kong dates 

![image](https://cloud.githubusercontent.com/assets/11516068/18824509/3af62886-83f5-11e6-8800-820e116e2e1d.png)

**Comment by blouiecubero** [comment]
working on this
