### ISSUE TITLE
[PUBLIC WEB] - User Side - Ascending Order of Preferred Schedule:

### ISSUE THREAD

**Issue by mque12** [tralulu/bugs#44]
**Scenario** 
After I clicked the [Review Booking], Hindi naka arrange yung Preferred Schedule. Medyo na confuse ako. 

**Expected Behavavior** 
Naka arrange siya Ascending Order :D 

_So Instead of :_ 
Thursday, September 29, 2016
Friday, September 30, 2016
Wednesday, November 16, 2016
Friday, November 18, 2016
Saturday, November 12, 2016
Tuesday, September 27, 2016
Wednesday, September 28, 2016

_It should be_
Tuesday, September 27, 2016
Wednesday, September 28, 2016
Thursday, September 29, 2016
Friday, September 30, 2016
Saturday, November 12, 2016
Wednesday, November 16, 2016
Friday, November 18, 2016

![image](https://cloud.githubusercontent.com/assets/11516068/18824594/dd0d8196-83f5-11e6-9d90-3487d42c41e8.png)

**Comment by blouiecubero** [comment]
working on this
