### ISSUE TITLE
[PUBLIC WEB] - User Side - Edit Main Details Horror

### ISSUE THREAD

**Issue by mque12** [tralulu/bugs#45]
**Scenario**
After clicking the Edit Main Details] , Nagopen ung modal, and 

> Lahat ng nilagay ko na date, and special request Nawala.......

**Expected Behavior**
Naka select and naka input ung mga details na naselect ko beforehand. 

![image](https://cloud.githubusercontent.com/assets/11516068/18824664/63a9ba58-83f6-11e6-82a2-7046146c25f2.png)

![image](https://cloud.githubusercontent.com/assets/11516068/18824697/a3675934-83f6-11e6-84a9-320293cf144f.png)

**Comment by kristianguevara** [comment]
Done 👍  Yet to be deployed on the test env for testing

![screen shot 2016-09-26 at 6 01 41 pm](https://cloud.githubusercontent.com/assets/3320659/18830447/51765f04-8413-11e6-82d7-77c634bf6576.png)
