### ISSUE TITLE
[PUBLIC WEB] - User Side - Importance of Tracking IDs

### ISSUE THREAD

**Issue by mque12** [tralulu/bugs#46]
**Scenario**
I dont know how important tracking IDs are, pero sa after Request booking ko lang siya na kikita. 
Since never pa ako naka receive ng email before about my booking, [NOT SURE IF ANDOON DIN]

*Expected Behavior**
I hope i can see it sa following areas:
1. Booking Details [Review Booking]
2. Email about Tralulu Receiving my Booking Request. 

![image](https://cloud.githubusercontent.com/assets/11516068/18825089/2ea1fd0e-83f9-11e6-9a9d-87f30742ab85.png)

**Comment by blouiecubero** [comment]
working on this
