### ISSUE TITLE
[PUBLIC WEB] Profile Edit Error

### ISSUE THREAD

**Issue by mque12** [tralulu/bugs#9]
*** Scenario ***
When I click my profile, I cannot do the following:
1. Edit my photo
2. Edit my Profile Details
3. Click the Edit Profile

I dont understand, bkit hindi parin ako verify, even if na confirm ko naman na sa email.
Also, May pre-coded info na ako. 

*** Expected Behavior ***
1. No photo sa start, so I can change my photo
2. I can edit my Profile
3. I can click the edit profile

when i confirmed sa email = verified naman na email ko.

![profile_edit_error](https://cloud.githubusercontent.com/assets/11516068/18458408/89104342-7993-11e6-9b51-c18afde8b7ed.png)

**Comment by kristianguevara** [comment]
Noted. Seems like a lot to do here :|

**Comment by mque12** [comment]
I'll close this one, since gumagana nmn na yung Edit profile Button. I'll create other tickets for the content part.
